version: 2.1

jobs:
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker and deploy to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed mattdoc/udagram-api-feed:latest
            docker push mattdoc/udagram-api-feed:latest
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user mattdoc/udagram-api-user:latest
            docker push mattdoc/udagram-api-user:latest
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend mattdoc/udagram-frontend:latest
            docker push mattdoc/udagram-frontend:latest
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy mattdoc/udagram-reverseproxy:latest
            docker push mattdoc/udagram-reverseproxy:latest

workflows:
  default:
    jobs:
      - build-docker
